### PR TITLE
feat(customization-rtl): use Vazirmatn font

### PR DESCRIPTION
**Pull request by okaeiz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

The current font of RTL strings in languages such as Persian or Arabic is not aesthetically pleasing and causes problems in readability in some screens.

## What is the new behavior?

The ideal solution is to use a readable font that is widely used in these languages. I have used [Vazirmatn](https://github.com/rastikerdar/vazirmatn) which a popular font.

## Notes for reviewers

I have not opened an issue for this. I decided to interact with the viewers under the PR, If I may. **This PR only changes the code in `customization-rtl` template**.

### CODE REVIEW

**Comment by BatuhanW** [comment]
Hey @okaeiz thanks for the PR. Since it's a PR against example, not creating issue is not a big problem.

Could you share before/after screenshots for this change?

**Comment by okaeiz** [comment]
> Hey @okaeiz thanks for the PR. Since it's a PR against example, not creating issue is not a big problem.
> 
> Could you share before/after screenshots for this change?

Sure thing. As you probably know, Github itself uses Vazirmatn font for Arabic and Persian characters. Take a look at the font's [official repository](https://github.com/rastikerdar/vazirmatn). Here are the screenshots:

#### Before


#### After



As you can notice, the letters are too close to each other in the default font. Since Arabic and Persian letters often have close dots and small dents, if they are too close, they can be indistinguishable. But Vazirmatn resolves the issue by putting adequate space between letters.

**Review by BatuhanW — APPROVED** [review]

**Review by alicanerdurmaz — APPROVED** [review]

**Comment by BatuhanW** [comment]
@okaeiz thanks for the contribution. Please see the message at the very beginning of PR description.

Following conventions makes our lives easier, keep in mind next time ❤️

**Comment by okaeiz** [comment]
> @okaeiz thanks for the contribution. Please see the message at the very beginning of PR description.
> 
> Following conventions makes our lives easier, keep in mind next time ❤️ 

I'll keep that in mind. Thank you.

**Pull request merged**
