### PR TITLE
fix(core): update debounce behavior on `onSearch` in `useSelect`

### PR DESCRIPTION
**Pull request by Dominic-Preap**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [x] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Debounce behavior on `onSearch`  is not working correctly when use inside `Controller` of react-hook-form causing re-fechting  multiple times.

## What is the new behavior?

Update `onSearch` to memoized value to prevent from re-fetching instead on return as inlined.

## Notes for reviewers

fix(core): update debounce behavior on `onSearch` in `useSelect`

Fixes https://github.com/refinedev/refine/issues/6096

### CODE REVIEW

**Review by BatuhanW — COMMENTED** [review]
Hey @Dominic-Preap thanks for the PR! Checked it briefly and it looks good. Could you also add tests? Then we can do a detailed review. 🚀

**Comment by Dominic-Preap** [comment]
@BatuhanW There are already test case on debounce function. My case is using `useSelect` inside `Controller` in react-hook-form, so I'm not familiar on how to write test case with that one. Could anyone can help on that?

**Comment by BatuhanW** [comment]
Hey @Dominic-Preap thanks for the clarification, we'll check it!

**Review by aliemir — APPROVED** [review]
Hey @Dominic-Preap, thank you for the PR! 🚀

I've updated one test case which was not responding to the changes in the `onSearch` prop because it lacked `rerender()` calls. Also added one more case to ensure `onSearch` prop can change without breaking the `debounce` interval. I think these are enough to test out the initial issue we're fixing here. 

Thanks again for the contribution! This will be included in our next release 👏 👏

**Pull request merged**
