### PR TITLE
fix(devtools-server): bump `express` to `^4.21.0`

### LINKED ISSUE #6321: [BUG] Moderate vulnerability in  `@refinedev/cli@2.16.38`
### Describe the bug

There is a moderate vulnerability on  `@refinedev/cli@2.16.38`
```sh
send  <0.19.0
Severity: moderate
send vulnerable to template injection that can lead to XSS - https://github.com/advisories/GHSA-m6fv-jmcg-4jfg
fix available via `npm audit fix --force`
Will install @refinedev/cli@2.5.3, which is a breaking change
node_modules/serve-static/node_modules/send
  serve-static  <=1.16.0
  Depends on vulnerable versions of send
  node_modules/serve-static
    express  4.0.0-rc1 - 5.0.0-beta.3
    Depends on vulnerable versions of serve-static
    node_modules/express
      @refinedev/cli  >=2.5.4
      Depends on vulnerable versions of @refinedev/devtools-server
      Depends on vulnerable versions of express
      node_modules/@refinedev/cli
      @refinedev/devtools-server  *
      Depends on vulnerable versions of express
      node_modules/@refinedev/devtools-server
```

### Steps To Reproduce

N/A

### Expected behavior

No vulnerability is present, use updated package

### Packages

- @refinedev/cli

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by arndom**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the new behavior?

fixes #6321

### CODE REVIEW

**Comment by arndom** [comment]
@BatuhanW For some reason `pnpm install` isn't updating the `pnpm-lock.yaml`.

it isn't even creating the `node_modules` after I deleted it, assuming that was the problem.

**Review by aliemir — CHANGES_REQUESTED** [review]
Thank you for the update @arndom, in addition to @BatuhanW's comment; can you please update the `express` version in `packages/devtools-server` (requires a changeset too) and `examples/mern-dashboard-server` to keep it consistent in the workspace? 🙏 


About `pnpm install`, are you running this command at the root of the repo? Were you able to run `pnpm install` successfully after you cloned it? 🤔

**Comment by arndom** [comment]
@aliemir I'll update the express version of the two 👍

Now that you mention it, I had tried `pnpm install` after the clone but it ran without generating the node_modules so I used `npm install` so that I could then run the changeset script.

- I've tried  `--force`, `--lockfile-only` options to no avail, 
- reinstalled `pnpm`, same issue; no node-modules or lockfile generation in the refine project
- created a blank project to see if `pnpm` was the issue but it was working normally there,

So I'm stuck at the moment.

Here are some details in case you need them:
- pnpm: v9.10.0
- node: v20.9.0
- os: win11

**Comment by arndom** [comment]
So I could only 'successfully' run `pnpm install` in the `master` branch to create the node modules folder. 

But if you delete the `pnpm-lock` and `node_modules` there is no generation of either; just as it was in my `fix` branch it runs without any output  (see bash in previous comment)

**Review by aliemir — APPROVED** [review]
Hey @arndom, I've just pushed couple of commits including the changes in `pnpm-lock.yaml`. I'll investigate the issue, it might be happening due to version changes in the packages and syncpack might been blocking the install 🤔

I've checked and saw that `express` is not actually used in `@refinedev/cli` anymore. I've removed the dependency and kept the other version updates as is. 

Thank you for your contribution 🙏

**Pull request merged**
