### PR TITLE
updated contribution section  in readme

### LINKED ISSUE #2918: [DOC] update readme
### Documentation issue

The contribution section isn't that clear.

### Describe the thing to improve

I want to convert this from 

If you discover a bug, please file a bug report at [issue](https://github.com/refinedev/refine/issues/new/choose).

to 

If you discover a bug, please file a bug report at [issue](https://github.com/refinedev/refine/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBUG%5D). 
If you want to fix a typo or update documentation, raise an issue [here](https://github.com/refinedev/refine/issues/new?assignees=&labels=documentation&template=documentation.yml&title=%5BDOC%5D)
If you want to propose a feature, raise a detailed issue with explanation [here](https://github.com/refinedev/refine/issues/new?assignees=&labels=enhancement&template=feature_request.yml&title=%5BFEAT%5D)

### Describe the solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
 
- updated contribution section in readme.

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues
closes #2918 

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

### CODE REVIEW

**Comment by omeraplak** [comment]
Hey @saimaheshtaduri ,
Thank you for your contribution! Would it be better if we reference this doc? 
https://refine.dev/docs/contributing/#ways-to-contribute

**Comment by saimaheshtaduri** [comment]
Yes. I'll also add the reference to this doc. 
@omeraplak

**Comment by saimaheshtaduri** [comment]
@omeraplak can you please review it now. 
Thanks :)

**Review by omeraplak — APPROVED** [review]

**Comment by omeraplak** [comment]
Thank you! 🚀

**Pull request merged**
