### PR TITLE
WIP: fix: ignoring npm ls error, closes #3348 

### LINKED ISSUE #3348: [BUG] Warning "Something went wrong when trying to get installed 'refine' packages."
### Describe the bug

When a refine project is created inside a monorepo with workspace feature enabled, the following warning appear when `refine dev` is executed: `Something went wrong when trying to get installed refine packages.`.

### Steps To Reproduce

- Create a blank project (not refine, but npm init)
- Go to the package.json and add the following key:
```
"workspaces": [
  "apps/*"
]
```
- Create and go to apps dir
- Create a refine project with `npm create refine-app@latest refine-app` using next.js + yarn
- Go to refine-app dir
- Run `yarn dev`
- See `Something went wrong when trying to get installed 'refine' packages.` on the console

### Expected behavior

Get the package list correctly and don't see the warning.

### Screenshot

_No response_

### Desktop

OS: Linux Mint
CLI version = 1.13.0

### Mobile

_No response_

### Additional Context

When refine project is created inside a monorepo, some packages are hoisted to the root and `npm ls` command throws an error marking some packages as `UNMET DEPENDENCY`, but the json with all the packages is returned. When you run `refine dev` an warning appear: `Something went wrong when trying to get installed refine packages.`. `yarn list` doesn't throw this, but yarn isn't an viable option for all the projects, we could ignore the npm error and get the package list.

### PR DESCRIPTION
**Pull request by vanflux**
Ignoring `npm ls` error.

### CODE REVIEW

**Comment by alicanerdurmaz** [comment]
Thanks for the PR 🙏 

In some cases, We want to throw errors. for example: `npx refine check-updates`
I believe we should handle `reject: true from the outside.

What do you think?

```tsx
type GetInstalledRefinePackages = {
    reject?: boolean;
};

export const getInstalledRefinePackages = async ({
    reject = true,
}: GetInstalledRefinePackages = {}) => {
    try {
        const execution = await execa("npm", ["ls", "--depth=0", "--json"], {
            reject,
        });
```

In `src/telemetry/index.ts`
```tsx 
packages: (await getInstalledRefinePackages({ reject: false })) || [],
```   

Also, can you provide a [changeset](https://refine.dev/docs/contributing/#changeset) please?

**Comment by vanflux** [comment]
> 



> Thanks for the PR pray
> 
> In some cases, We want to throw errors. for example: `npx refine check-updates` I believe we should handle `reject: true` from the outside.
> 
> What do you think?
> 
> ```tsx
> interface GetInstalledRefinePackages {
>     reject?: boolean;
> };
> 
> export const getInstalledRefinePackages = async ({
>     reject = true,
> }: GetInstalledRefinePackages = {}) => {
>     try {
>         const execution = await execa("npm", ["ls", "--depth=0", "--json"], {
>             reject,
>         });
> ```
> 
> In `src/telemetry/index.ts`
> 
> ```tsx
> packages: (await getInstalledRefinePackages({ reject: false })) || [],
> ```
> 
> Also, can you provide a [changeset](https://refine.dev/docs/contributing/#changeset) please?

But the point is, npm ls is throwing an error wrongly, an error that doesn't exist, the packages are installed. I could add these changes, but the telemetry will not get package versions for monorepos even if working.

**Comment by alicanerdurmaz** [comment]
> > 
> 
> > Thanks for the PR pray
> > In some cases, We want to throw errors. for example: `npx refine check-updates` I believe we should handle `reject: true` from the outside.
> > What do you think?
> > ```tsx
> > interface GetInstalledRefinePackages {
> >     reject?: boolean;
> > };
> > 
> > export const getInstalledRefinePackages = async ({
> >     reject = true,
> > }: GetInstalledRefinePackages = {}) => {
> >     try {
> >         const execution = await execa("npm", ["ls", "--depth=0", "--json"], {
> >             reject,
> >         });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In `src/telemetry/index.ts`
> > ```tsx
> > packages: (await getInstalledRefinePackages({ reject: false })) || [],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, can you provide a [changeset](https://refine.dev/docs/contributing/#changeset) please?
> 
> But the point is, npm ls is throwing an error wrongly, an error that doesn't exist, the packages are installed. I could add these changes, but the telemetry will not get package versions for monorepos even if working.

Actually, we need to fix `npm ls` not suppress errors am I right? 👀
Let's continue with this method, probably we should find another way to detect installed packages. I will discuss this with the core team tomorrow. Thanks for the issue 🚀 

If you have another idea to find installed packages, please let me know 🙏

**Comment by vanflux** [comment]
> > > 
> > 
> > 
> > > Thanks for the PR pray
> > > In some cases, We want to throw errors. for example: `npx refine check-updates` I believe we should handle `reject: true` from the outside.
> > > What do you think?
> > > ```tsx
> > > interface GetInstalledRefinePackages {
> > >     reject?: boolean;
> > > };
> > > 
> > > export const getInstalledRefinePackages = async ({
> > >     reject = true,
> > > }: GetInstalledRefinePackages = {}) => {
> > >     try {
> > >         const execution = await execa("npm", ["ls", "--depth=0", "--json"], {
> > >             reject,
> > >         });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In `src/telemetry/index.ts`
> > > ```tsx
> > > packages: (await getInstalledRefinePackages({ reject: false })) || [],
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also, can you provide a [changeset](https://refine.dev/docs/contributing/#changeset) please?
> > 
> > 
> > But the point is, npm ls is throwing an error wrongly, an error that doesn't exist, the packages are installed. I could add these changes, but the telemetry will not get package versions for monorepos even if working.
> 
> Actually, we need to fix `npm ls` not suppress errors am I right? eyes Let's continue with this method, probably we should find another way to detect installed packages. I will discuss this with the core team tomorrow. Thanks for the issue rocket
> 
> If you have another idea to find installed packages, please let me know pray

Could we get installed packages from package.json? Or is this not a good idea?

**Comment by alicanerdurmaz** [comment]
Hi @vanflux, we will research other ways to detect installed packages. we'll probably find it in 1-2 days. We'll be able to use your solution during this time.

Thank you again for helping us 🙏

**Review by alicanerdurmaz — APPROVED** [review]

**Review by aliemir — APPROVED** [review]

**Review by omeraplak — APPROVED** [review]

**Pull request merged**
