### PR TITLE
refactor(packages): update package.json configuration with proper ESM and CJS values

### LINKED ISSUE #5202: [FEAT] Vite support on  Remix experimental
### Describe the bug

Trying to use remix in vite support experimental [link](https://remix.run/docs/en/main/future/vite)  and refine giving issue on  `[vite] Error when evaluating SSR module /app/root.tsx: failed to import "@refinedev/remix-router"`

### Steps To Reproduce

create remix on vite using it docs and manually add refine base on the instruction docs based

### Expected behavior

refine should be working and no issue 

### Screenshot

_No response_

### Desktop

_No response_

### Mobile

_No response_

### Additional Context

I  know its remix support is experimental but it no hurt if we could support it in early stage thanks

### LINKED ISSUE #5734: [BUG] Remix (SPA) Support
### Describe the bug

The current build process of refine packages makes it incompatible with Remix SPA, and possibly? more.

This has been tested on Remix 2.8.0.

The following steps need to be taken:

- Disable minify on all repos in tsup `esbuildOptions` via `options.minify = false;` (remix SPA does a sort-of 1 time SSR eval, running `Refine` through a node-js server which needs the ESM import, unminified)
- Disable tsbuild `--legacyOutput`.
- Add export maps with the esm `import` pointing to a `.mjs` file (this actually really matters)
  - Ensure export maps have typings as well.
- Replace `lodash-es` and `papaparse` at a minimum to use `.js` extensions when imported
- Update commands in `packages/cli/src/commands/runner` as `remix-serve` no longer exists and needs to use `remix vite:*`?

You can see a debug branch with many of these changes at https://github.com/LumeWeb/refine/tree/remix for reference.

### Steps To Reproduce

Try to build a remix SPA with any basic refine example.

### Expected behavior

It should run the dev server and build correctly.

### Packages

All refine packages are likely impacted if they are to be used within remix.

### Additional Context

_No response_

### LINKED ISSUE #5770: [REFACTOR] Proper ESM & CJS bundles
Currently Refine packages exports ESM and CJS bundles but due to the mis configurations in `package.json` files, these bundles may falsely interpreted by bundlers. Improving Refine's package configurations with proper `exports` fields and extensions is crucial for latest dev environments.

### LINKED ISSUE #5772: [BUG] Wrong types in `@refinedev/react-router-v6` when using legacy router
### Describe the bug

When using the legacy router provider from `@refinedev/react-router-v6/legacy`, types are inferred as the new router provider and conflicts when using `legacyRouterProvider` prop of `<Refine />`

### Steps To Reproduce

- Import `routerProvider` from `@refinedev/react-router-v6/legacy`,
- Pass `routerProvider` to `legacyRouterProvider` prop of `<Refine />`
- TS throws errors about mismatching types

### Expected behavior

Proper types to be exported in `/legacy` exports.

### Packages

- @refinedev/react-router-v6

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aliemir**
- Updated package configuration for ESM and CJS
- Updated `tsup` config to bundle with proper extensions
- Removed unused `iife` bundle
- Added `@tabler/icons-react` CJS replacement plugin
- Replaced `@refinedev/live-previews` scope imports with require
- Fixed `papa parse` and `lodash-es` imports in `@refinedev/core` for CJS and ESM
- Moved declaration generation to a separate script and shared between all published packages with proper extensions
- Fixed `test-id` removal plugin for new extensions.

### CODE REVIEW

**Comment by aliemir** [comment]
Due to these changes (and also prior changes in ts versions) app built with `react-scripts` might have issues with importing ESM bundles of Refine packages. 

This is due to the default webpack configuration of `react-scripts` which requires extensions even for the imports made from files in `node_modules`.

To address this issue, you will need to update the webpack configuration and mark `fullySpecified` as `false` for `js` and `mjs` files.

Below configuration is what we've used in our examples with `react-scripts` and used `@craco/craco` to update the webpack configuration:

```js
// craco.config.js
module.exports = {
  webpack: {
    configure: {
      module: {
        rules: [
          {
            test: /.m?js$/,
            resolve: {
              fullySpecified: false,
            },
          },
        ],
      },
    },
  },
};
```

**Comment by pcfreak30** [comment]
@aliemir is there a reason minify is not disabled. thats one of the core issues.

`Disable minify on all repos in tsup esbuildOptions via options.minify = false; (remix SPA does a sort-of 1 time SSR eval, running Refine through a node-js server which needs the ESM import, unminified)`

**Comment by aliemir** [comment]
> @aliemir is there a reason minify is not disabled. thats one of the core issues.
> 
> `Disable minify on all repos in tsup esbuildOptions via options.minify = false; (remix SPA does a sort-of 1 time SSR eval, running Refine through a node-js server which needs the ESM import, unminified)`

Hey @pcfreak30, we've tried both minified and unminified builds when making the changes in the exports/configuration. Since now the exports are fixed and properly formatted for esm and cjs we haven't had any issues with minified builds when testing it with Remix and remix in spa mode. Only issue we've encountered is related with Material UI and their ESM builds/configuration, other than that we didn't had any issues. 

Since the release is done, can you check if your case is also resolved/works with minified builds? If not, you can open up an issue and we'll try to make appropriate changes to fix. 🙏

**Comment by bombillazo** [comment]
This PR is causing us this issue now:

```sh
 Error: Cannot find module '/Users/Projects/Code/appnode_modules/next/router' imported from /Users/Projects/Code/node_modules/@refinedev/nextjs-router/dist/pages.mjs
Did you mean to import next/router.js?
```

**Pull request merged**
