### PR TITLE
feat: control for navigation tweak

### LINKED ISSUE #4310: [FEAT]: Provide a way to tweak navigation for resources
### Is your feature request related to a problem? Please describe.

It would be good if we can forcefully render on Resource click. For example, I'm working on a big-scale ERP-like software and I've created some resources like the following.

```javascript
//...some jsx stuff
resources={[
  {
    name: 'dashboard',
    list: '/',
    meta: {
      label: 'Dashboard',
      icon: <Dashboard />
    }
  },
  {
    name: 'weight-calculator',
    list: WEIGHT_CALCULATOR_PATH,
    meta: {
      label: 'Weight Calculator',
      parent: 'Tools',
      icon: <Calculate />
    }
  },
  {
    name: 'weight-calculator-records',
    list: WEIGHT_CALCULATOR_RECORDS_PATH,
    meta: {
      label: 'Calculation Records',
      parent: 'Tools',
      icon: <Feed />
    }
  },
  {
    name: 'roles-list',
    list: ROLES_LIST_PATH,
    meta: {
      label: 'Roles',
      icon: <ManageAccounts />
    }
  }
]}
```

Currently, it seems there is no easier way to achieve the reload on the menu click. What I mean here is that if my current tab is `Weight Calculator` and I click on it again, It just navigates to the path but it doesn't trigger remounting. Because of this, the UI gets reset but the form values stay persistent!

### Describe alternatives you've considered

I can do a nasty workaround using some sort of `useEffect` and state to check if the values have been reset and then upon that, I can reset the form as well so it just seems a bit of a hacky way to do this!

### Additional context

Screenshot_63
Screenshot_64

### Describe the thing to improve

I have 2 suggestions.
There can be an optional prop that ignores active tab click, So if the route and resource are on the same URL, Clicking on a resource will not trigger route change if this prop has been turned on

Alternatively, we can have a prop similar to `navigationProps` which contains settings related to navigations like `reload: boolean` etc!

### PR DESCRIPTION
**Pull request by Mr0nline**
When we rely on the mount effects, Clicking on the same sider item will result in a page reload due to them being linked. We need to prevent the default behavior if the item is selected so that it doesn't remount the components!

### Test plan (required)

I've tested all 5 packages touched by changes. `core, antd, mui, mantine and chakra-ui`!

### Closing issues

closes #4310 

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

**Comment by Mr0nline** [comment]
@aliemir, Sorry for the ping but just wondering if I require any further changes on this or not :)

**Comment by omeraplak** [comment]
> @aliemir, Sorry for the ping but just wondering if I require any further changes on this or not :)

Hey @Mr0nline ,
Sorry for the delay. I think we'll be able to review it next week. Thank you for your patience ⚡️

**Review by aliemir — CHANGES_REQUESTED** [review]
Hey @Mr0nline, thank you for the PR! Sorry for the late review 🙏 Like @alicanerdurmaz stated, can we switch to `pointer-events: none` from `onClick`? Looks like a better way to handle the disabled status without blocking the event. 

Waiting for your changes, we're hoping to get this one released this week 🚀 🚀

**Comment by aliemir** [comment]
> JFI: I'm planning to do the required changes by this Saturday as it's when I'm free mostly for! I hope that's fine with the release plan!

No problem on our side! Thank you for the response! 🚀  We'll review the changes when they're ready and merge it 🙏

**Comment by Mr0nline** [comment]
@aliemir I've updated the PR as requested! Let me know if it require any more changes :crossed_fingers:

**Review by BatuhanW — CHANGES_REQUESTED** [review]
Hello @Mr0nline thanks for the PR!

Can we update relevant unit tests to test the new behaviour, with & without props?

**Comment by Mr0nline** [comment]
> Hello @Mr0nline thanks for the PR!
> 
> Can we update relevant unit tests to test the new behaviour, with & without props?

@BatuhanW Sure but I've haven't quite wrote any tests, So could you guide me on which changes are required and how it should be done or if possible could you please write the tests if it's not much time consuming! It's just that I might not become available till next friday as weekends are almost over in my timezone :disappointed: 

Let me know if there's some definitive steps or guide which I can follow to update the test and I'll give it a go :crossed_fingers:

**Comment by BatuhanW** [comment]
> > Hello @Mr0nline thanks for the PR!
> > Can we update relevant unit tests to test the new behaviour, with & without props?
> 
> @BatuhanW Sure but I've haven't quite wrote any tests, So could you guide me on which changes are required and how it should be done or if possible could you please write the tests if it's not much time consuming! It's just that I might not become available till next friday as weekends are almost over in my timezone 😞
> 
> Let me know if there's some definitive steps or guide which I can follow to update the test and I'll give it a go 🤞

Hey @Mr0nline no worries, and thanks for the contribution! We'll release it soon

**Review by BatuhanW — APPROVED** [review]

**Comment by Mr0nline** [comment]
Thanks @alicanerdurmaz for writing tests! 🙏🏻

**Review by aliemir — APPROVED** [review]

**Pull request merged**
