### PR TITLE
fix(core): useTranslate to import from @hooks in auth login page

### LINKED ISSUE #6140: [BUG] Using Swizzle for AuthPage in Next.js generates code with i18n but the folder hooks is not created
### Describe the bug

I created a Next.js Refine project and headless UI. Used swizzle to customize the AuthPage and it imports a hook called useTranslate hook:

```js
import React, { useState } from "react";
import {
  useActiveAuthProvider,
  useLink,
  useLogin,
  useRouterContext,
  useRouterType,
  LoginFormTypes,
  LoginPageProps,
} from "@refinedev/core";

import { useTranslate } from "@hooks/i18n"; //Cannot find module '@hooks/i18n' or its corresponding type declarations.
```

Where and how should this be created to fix it?

### Steps To Reproduce

1. Create a Nextjs + Headless UI project from site.
2. Run `npm run refine swizzle`
3. Select AuthPage
4. Go to the generated file called login.tsx in components/pages/auth/components folder
5. You should see an error "Cannot find module '@hooks/i18n' or its corresponding type declarations."

### Expected behavior

It is supposed to add the hooks folder with the useTranslate hook.

### Packages

"@refinedev/cli": "^2.16.21",
"@refinedev/core": "^4.47.1",
"@refinedev/devtools": "^1.1.32",
"@refinedev/kbar": "^1.3.6",
"@refinedev/nextjs-router": "^6.0.0",
"@refinedev/react-hook-form": "^4.8.14",
"@refinedev/react-table": "^5.6.6",
"@refinedev/simple-rest": "^5.0.1",

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Sarfraz-droid**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [X] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the new behavior?

fixes (#6140 )

### CODE REVIEW

**Review by aliemir — CHANGES_REQUESTED** [review]
Hey @Sarfraz-droid thank you for your contribution! 🚀 Changes in the `auth/components/login/index.tsx` is correct but the same needs to be applied to other pages as well (`register`, `forgotPassword` and `updatePassword` components) Can you work on those as well? 🙏

**Comment by Sarfraz-droid** [comment]
Sure! Will do

**Comment by Sarfraz-droid** [comment]
Hey @aliemir , I think it's already fixed in other pages. Are there any other changes needed?

https://github.com/refinedev/refine/blob/master/packages%2Fcore%2Fsrc%2Fcomponents%2Fpages%2Fauth%2Fcomponents%2FupdatePassword%2Findex.tsx#L4

https://github.com/refinedev/refine/blob/master/packages%2Fcore%2Fsrc%2Fcomponents%2Fpages%2Fauth%2Fcomponents%2Fregister%2Findex.tsx#L8

https://github.com/refinedev/refine/blob/master/packages%2Fcore%2Fsrc%2Fcomponents%2Fpages%2Fauth%2Fcomponents%2FforgotPassword%2Findex.tsx#L8

**Review by aliemir — APPROVED** [review]
You're right @Sarfraz-droid, no changes necessary on these files 🤦 Thank you for your response! 🙏  This PR will be included in our next release 🚀

**Pull request merged**
