### PR TITLE
Hyperlinked the image in readme.md

### PR DESCRIPTION
**Pull request by Abubakrce19**
Now the user can go to the "http://localhost:3000" just by one click on image. Minor but impactful
Thank you!!

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

### CODE REVIEW

**Comment by omeraplak** [comment]
Thank you @Abubakrce19

**Comment by Abubakrce19** [comment]
> 
@omeraplak 
Thanks to you too!!
Am I Eligilble for the swags now??(My 2 Prs got merged)
Do I have to Fill any registration form??

**Comment by omeraplak** [comment]
Yes 🎁 Could you write on [Discord](http://discord.gg/refine)?

**Comment by Abubakrce19** [comment]
> 

Sure!!
Already a memeber

**Pull request merged**
