### PR TITLE
feat: added setAction feature #6451

### PR DESCRIPTION
**Pull request by AYUSHKUMARGUPTA**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the new behavior?

fixes (issue)

## Notes for reviewers
Added setAction function to get action dynamically

Usage 
`const { setAction, show, modalProps } = useModalForm({
  action: "create",
});

// Call setAction to change the action type
const handleEdit = () => {
  setAction("edit");
  show();
};

const handleCreate = () => {
  setAction("create");
  show();
};`

### CODE REVIEW

**Review by BatuhanW — COMMENTED** [review]
Hey @AYUSHKUMARGUPTA thanks for the PR!

Could you add tests to makae sure new behaviour works as expected and update documentation so people will be aware of this feature?

**Comment by AYUSHKUMARGUPTA** [comment]
@BatuhanW Sure will get this updated

**Comment by aress31** [comment]
It would be better to add a metadata prop to the show method this way any data can be passed down...

**Comment by AYUSHKUMARGUPTA** [comment]
Updated the code for build failure.

**Comment by aliemir** [comment]
Thank you for the PR @AYUSHKUMARGUPTA, I've just left a comment to the issue https://github.com/refinedev/refine/issues/6451#issuecomment-2497667690 and tried to explain the missing steps in the implementation of this feature. For now, we've decided to keep this feature on hold and include it in our next release roadmap. 🙏

**Pull request closed without merging**
