### PR TITLE
feat: add onSiderCollapsed to RefineThemedLayoutV2Props

### LINKED ISSUE #6508: [FEAT] ThemedSiderV2 Persist Collapsed State
### Is your feature request related to a problem? Please describe.

Would be nice to persist out of the box the collapsed state, or add an option to do so, maybe a "peristCollapsed" boolean. This would avoid having to write extra code for this important UX feature.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Describe the thing to improve

See above.

### PR DESCRIPTION
**Pull request by OmkarBansod02**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

The current behavior is that the collapsed state of the sider is not persisted out of the box. Developers need to write additional code to manage and persist the collapsed state, which adds extra effort for implementing this common UX feature.

## What is the new behavior?

The sider now supports out-of-the-box persistence of the collapsed state through the new onSiderCollapsed boolean option. This enhancement eliminates the need for additional code to manage and persist the collapsed state, improving the developer experience and enhancing UX.

fixes #6508

## Notes for reviewers

I’ve added the `onSiderCollapsed` feature to make it easier to persist the sider's collapsed state. I haven’t written tests for it yet but can definitely add them if needed. just let me know .

### CODE REVIEW

**Comment by alicanerdurmaz** [comment]
Hello @OmkarBansod02 thanks for improving Refine, everything looks great!

If you have time can you add documentation for these changes? after that I belive this PR will be ready for release.

**Comment by OmkarBansod02** [comment]
> Hello @OmkarBansod02 thanks for improving Refine, everything looks great!
> 
> If you have time, can you add documentation for these changes? After that, I believe this PR will be ready for release.

Yeah sure ! @alicanerdurmaz Can you please give me some hints Or any reference point to start from.

**Comment by alicanerdurmaz** [comment]
> > Hello @OmkarBansod02 thanks for improving Refine, everything looks great!
> > If you have time, can you add documentation for these changes? After that, I believe this PR will be ready for release.
> 
> Yeah sure ! @alicanerdurmaz Can you please give me some hints Or any reference point to start from.

We are adding props documentation in the following sections:

Material UI:
- live link: https://refine.dev/docs/ui-integrations/material-ui/components/themed-layout/#props
- source code of doc: https://github.com/refinedev/refine/blob/main/documentation/docs/ui-integrations/material-ui/components/themed-layout/index.md#props

Ant Design:
- live link: https://refine.dev/docs/ui-integrations/ant-design/components/themed-layout/
- source code of doc: https://github.com/refinedev/refine/blob/main/documentation/docs/ui-integrations/ant-design/components/themed-layout/index.md

Mantine:
- live link: https://refine.dev/docs/ui-integrations/mantine/components/themed-layout/
- source code of doc: https://github.com/refinedev/refine/blob/main/documentation/docs/ui-integrations/mantine/components/themed-layout/index.md

Chakra UI:
- live link: https://refine.dev/docs/ui-integrations/chakra-ui/components/themed-layout/
- source code of doc: https://github.com/refinedev/refine/blob/main/documentation/docs/ui-integrations/chakra-ui/components/themed-layout/index.md

**Comment by OmkarBansod02** [comment]
Hey @alicanerdurmaz , I've added documentation for the ` onSiderCollapsed`  under the  `Ant Design ` provider section.
It includes: 
- A description of the prop in the Sider Props table.
- An example demonstrating how to use the `onSiderCollapsed` .  

Could you please review this and let me know if it aligns with the expected style and content? so i can move forward with other UI docs .

**Pull request merged**
