### PR TITLE
feat(hasura): implement _not operator in filters

### LINKED ISSUE #5689: [FEAT] support _not operator query for hasura data provider
### Is your feature request related to a problem? Please describe.

I tried to make the following query with filters and hasura data provider

```
query query {
  event(where: {_not: {group_event: {event__id: {_is_null: false}}}}, limit: 10) {
    id
    group_event {
      event__id
    }
  }
}
```

But the "not" operator doesn't seem to be supported in filter management (https://refine.dev/docs/advanced-tutorials/data-provider/handling-filters/#crudfilters). 

### Describe alternatives you've considered

I used the graphql query in the meta field
https://refine.dev/docs/data/packages/hasura/#developer-experience

### Additional context

_No response_

### Describe the thing to improve

Implements the not operator ?

### PR DESCRIPTION
**Pull request by rilrom**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

The `_not` operator is not supported in Hasura filters.

## What is the new behavior?

The `_not` operator is supported in Hasura filters.

Resolves #5689.

## Notes for reviewers

In order to keep these changes within the scope of the request I have implemented Hasura specific types that include `_not` instead of using the global `CrudFilter`.

There are other data providers that could also take advantage of the `_not` filter (e.g. strapi-v4, supabase, airtable).

I'm unsure whether the `_not` operator can be included in `CrudFilter` safely at this stage however it might be worth considering in the future in order to cover other use cases. I'm open to any thoughts or suggestions on this.

### CODE REVIEW

**Review by BatuhanW — CHANGES_REQUESTED** [review]
Hey @rilrom let's not randomly check those boxes, if you haven't write any test or didn't update the documentation.

- Make sure the new file in `src/types/index.ts` is included in `packages/hasura/refine.config.js`. So when users swizzle hasura package, CLI will also copy.
- Add tests covering your new operator.
- Check relevant sections of documentation if any update is needed.

**Comment by rilrom** [comment]
Hi @BatuhanW, thanks for the review.

Apologies, it looks like I've misunderstood the checkboxes. I checked them as I didn't see a need for additional tests or documentation in this instance.

The existing tests cover the usecases of `_and` and `_or` which is the same category that `_not` falls into. If necessary I can adjust the tests to be more explicit.

I also did not see any mention of filters in the existing hasura documentation.

**Comment by BatuhanW** [comment]
> Hi @BatuhanW, thanks for the review.
> 
> 
> 
> Apologies, it looks like I've misunderstood the checkboxes. I checked them as I didn't see a need for additional tests or documentation in this instance.
> 
> 
> 
> The existing tests cover the usecases of `_and` and `_or` which is the same category that `_not` falls into. If necessary I can adjust the tests to be more explicit.
> 
> 
> 
> I also did not see any mention of filters in the existing hasura documentation.

Hey @rilrom no worries. But let's write tests anyway. 🚀

**Comment by rilrom** [comment]
Hi @BatuhanW

I decided to remove the use of `src/types/index.ts` to keep consistent with the placement of types throughout the rest of the hasura package.

I've also implemented a test to cover the use of the `not` operator.

**Review by BatuhanW — APPROVED** [review]
LGTM 👍🏼 cc @aliemir @alicanerdurmaz

**Pull request merged**
