### PR TITLE
feat(core): handle query filters in ListButton 

### LINKED ISSUE #6528: [FEAT]`ListButton` from `@refinedev/mui` doesn't implement the `meta` query properly
### Describe the bug

- I tried to use the ListButton to route to the list page with some query filters but it completely overlooks the filters.
-  Here is what I did
```tsx
<ListButton
      resource="contacts"
      meta={{
        query: {
          filters: [
            {
              field: filterField,
              operator: "contains",
              value: filterValue
            }
          ]
        }
      }}
    >
      Contacts
    </ListButton>
```
- But instead of having the filters be part of the URL query, there is only `/contacts`
------ 
- I followed the component definition and the error may be how the `useNavigationButton` from `@refinedev/core` is handling the meta prop
```tsx
  const navigation = useNavigation();

  const to = React.useMemo(() => {
    if (!resource) return "";
    switch (props.action) {
      case "create":
      case "list": // here
        return navigation[`${props.action}Url`](resource, props.meta);
      default:
        if (!id) return "";
        return navigation[`${props.action}Url`](resource, id, props.meta);
    }
  }, [resource, id, props.meta, navigation[`${props.action}Url`]]);
```
- I believe the issue is in the definition of `listUrl` inside the definition of `useNavigation`, though I'm unsure since I haven't indepthly gone through the source.

### Steps To Reproduce

- Attempt to navigate to a list page using:
```tsx
<ListButton
      resource="contacts"
      meta={{
        query: {
          filters: [
            {
              field: filterField,
              operator: "contains",
              value: filterValue
            }
          ]
        }
      }}
    >
      Contacts
    </ListButton>
```

### Expected behavior

- the list button works with url query filters

### Packages

- "@refinedev/mui": "^5.14.4",
- "@refinedev/core": "^4.47.1",

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by OmkarBansod02**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

The` listUrl ` function in `useNavigation` hook doesn't properly process query filters passed through the `meta` parameter, resulting in missing query parameters in the generated URL 

## What is the new behavior?
The` listUrl ` function now correctly processes and includes query parameters from the `meta `object when generating URLs, enabling proper query filter support for any component that uses the `useNavigation` hook

fixes #6528

### CODE REVIEW

**Review by aliemir — CHANGES_REQUESTED** [review]
Hey @OmkarBansod02 thank you for the PR! I've left a comment about the required implementation in the issue https://github.com/refinedev/refine/issues/6528#issuecomment-2513816965 Can you please check it out and update your PR? 🙏

**Review by aliemir — CHANGES_REQUESTED** [review]
Thank you for the update @OmkarBansod02! Can you also add this to `showUrl`? 🙏

**Review by aliemir — APPROVED** [review]

**Comment by BatuhanW** [comment]
Hey @OmkarBansod02 we accidently merged your PR to `main`, instead of `releases/december-2024` branch. Can you re-open your PR ?

**Comment by BatuhanW** [comment]
> > Hey @OmkarBansod02 we accidently merged your PR to `main`, instead of `releases/december-2024` branch. Can you re-open your PR ?
> 
> Yeah sure @BatuhanW . Should I revert this PR first?

No, we took care of it.

**Comment by OmkarBansod02** [comment]
hey @BatuhanW , I  re-open new PR [#6558] and reapplied the changes from the previous PR [#6530 ]. let me know if anything else needed. 🚀

**Pull request merged**
