### PR TITLE
docs(ant-design): useForm hook documentation fix for props

### PR DESCRIPTION
**Pull request by Tejas-Gawde**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [ ] Tests for the changes have been added
- [x] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?
Shows refineCoreProps wrapped around submitOnEnter. 

## What is the new behavior?
Doesn't show that anymore.

### CODE REVIEW

**Review by aliemir — CHANGES_REQUESTED** [review]
Hey @Tejas-Gawde thank you for the contribution! The same usage is repeated in other sections of the Properties section and also one in FAQ of the same page. Can you update them as well? 🙏

**Comment by aliemir** [comment]
Hey @Tejas-Gawde, I meant in the same file there are other uses of `refineCoreProps` scope which is not valid for `useForm` of `@refinedev/antd`. 

Check out these for example: 

https://github.com/refinedev/refine/blob/0099f4a9db41e4f91a256846c1455381ceafcbbc/documentation/docs/ui-integrations/ant-design/hooks/use-form/index.md?plain=1#L436-L438

https://github.com/refinedev/refine/blob/0099f4a9db41e4f91a256846c1455381ceafcbbc/documentation/docs/ui-integrations/ant-design/hooks/use-form/index.md?plain=1#L1095-L1106

Let me know if you can work on these and other occurrences. 🙏

**Comment by Tejas-Gawde** [comment]
Yeah sure I will do it

**Review by alicanerdurmaz — APPROVED** [review]

**Review by aliemir — APPROVED** [review]
Thank you for your contribution @Tejas-Gawde 🙏

**Pull request merged**
