### PR TITLE
feat(kbar): added shortcuts to kbar actions

### PR DESCRIPTION
**Pull request by grigoreo-fox**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?
There is now shortcuts in kbar 

## What is the new behavior?
Shortcuts applied by default:

- List: First letter from resource name
- Create: "c" (from list page)
- Edit: "e"
- Delete: "d" (opens delete group)

Shortcuts can be customized by passing shortcuts object to resource meta like this.

```tsx
resources={[
    {
      name: "categories",
      list: "/categories",
      create: "/categories/create",
      meta: {
        shortcuts: {
          create: ["n"], // Now, pressing "n" triggers the creation of a category.
        },
      },
    },
  }]}
```

Resolves #5750

## Notes for reviewers

I am not sure whether to enable/disable this feature by default.
Perhaps it would be worth adding a prop to `RefineKbar` compenent
```tsx
<RefineKbar useShortcuts={true/false}>
```

I would be happy to discuss this and am ready to add documentation and update the example.

In the process of working, I noticed that the `list` action is displayed on the `list` page.
However, the test ["do not register the list resource when you are on the list page"](https://github.com/refinedev/refine/blob/8fe789d96e35d3af11d5696ac465032735434df1/packages/kbar/src/hooks/useRefineKbar/index.spec.tsx#L84C9-L84C72) passes successfully.

### CODE REVIEW

**Review by BatuhanW — COMMENTED** [review]
Hey @grigoreo-fox thanks for the PR and following guidelines with commit messages and changesets!

Could you update an example with e2e spec, which uses KBar to test these changes? You can add additional test case where user presses these shortcuts and check if it redirects corretly or the dialog pops up.

We also need to update the documentation to mention this feature!

Best.

**Comment by grigoreo-fox** [comment]
Hello @BatuhanW
What do you think about "Notes for reviewers" section?

-  ability to enable/disable, default state?
- confusion with current implementation of list action

**Comment by BatuhanW** [comment]
Hey @grigoreo-fox 

> I am not sure whether to enable/disable this feature by default.

Let's have it disabled by default, opt-in to enable.

> In the process of working, I noticed that the list action is displayed on the list page.

I think this is a bug and probably those tests weren't written reliably. 😞

**Comment by BatuhanW** [comment]
Hey @grigoreo-fox, we've merged `releases/april` branch, so your PR is closed. Could you re-open your PR?

**Comment by grigoreo-fox** [comment]
Hello, @BatuhanW!
My project, where I use Refine is paused now.
I will continue the work on it in a month, and also will continue contributing here.
I have couple more Ideas about Refine, still thinking on a proper ways to implement.

**Pull request closed without merging**
