### PR TITLE
fix(docs): add missing dependency to mui tutorial

### PR DESCRIPTION
**Pull request by BatuhanW**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## What is the current behavior?

Example at mui tutorial is failing at https://refine.dev/tutorial/ui-libraries/layout/material-ui/react-router/

Screenshot 2024-03-20 at 10 53 00

## What is the new behavior?

Fixed.

### CODE REVIEW

**Review by alicanerdurmaz — APPROVED** [review]

**Comment by Nosferatu31** [comment]
@BatuhanW I still am having this error, was it already deployed? :)

**Comment by BatuhanW** [comment]
@Nosferatu31 I guess it's a similar, but different issue this time. We may need to update mui versions. We'll check it tomorrow.

**Comment by Nosferatu31** [comment]
> @Nosferatu31 I guess it's a similar, but different issue this time. We may need to update mui versions. We'll check it tomorrow.

Thank you @BatuhanW

**Comment by BatuhanW** [comment]
> > @Nosferatu31 I guess it's a similar, but different issue this time. We may need to update mui versions. We'll check it tomorrow.
> 
> Thank you @BatuhanW

@Nosferatu31 It should be fixed now.

**Comment by Nosferatu31** [comment]
@BatuhanW thank you, I've checked and it's all fixed now 👍

**Pull request merged**
