### PR TITLE
feat(ci): refactor workflows

### PR DESCRIPTION
**Pull request by BatuhanW**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the new behavior?

fixes # (issue)

### CODE REVIEW

**Review by aliemir — APPROVED** [review]

**Comment by BatuhanW** [comment]
/deploy app-crm-minimal, with-nextjs, finefoods-client, win95

**Pull request merged**
