### PR TITLE
fix(btn): changed opacity and height of btn to make responsive in store

### LINKED ISSUE #2739: [FEAT]change the opacity of the slider buttons in mobile mode.
Screenshot 2022-10-13 at 1 36 09 PM

### PR DESCRIPTION
**Pull request by s-vamshi**
**Before:**
image
image

**After:**
image
image

### Closing issues

closes #2739

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

**Comment by s-vamshi** [comment]
@aliemir @omeraplak 
Is the height of the button ok in mobile view or should I reduce it?

**Comment by omeraplak** [comment]
> @aliemir @omeraplak Is the height of the button ok in mobile view or should I reduce it?

Hey @s-vamshi ,
You can reduce it

**Comment by s-vamshi** [comment]
@omeraplak can you check now?

**Review by omeraplak — APPROVED** [review]
Thank you! 🚀

**Pull request merged**
