### PR TITLE
feat: implement camelCase naming convention for Hasura

### LINKED ISSUE #3482: [FEAT] Hasura naming conventions (camelCase)
### Is your feature request related to a problem? Please describe.

Currently we hard-code snake-case operation and type names.

But recently Hasura released a [setting](https://hasura.io/docs/latest/schema/postgres/naming-convention/) where you can switch from snake_case to camelCase.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Describe the thing to improve

The [Hasura DataProvider](https://github.com/refinedev/refine/blob/master/packages/hasura/src/dataProvider/index.ts) should be refactored to support camelCase.

### PR DESCRIPTION
**Pull request by mattbho**
All methods for the Hasura Data provider now support the camelCase `graphql-default` naming convention.

The data provider now accepts a `namingConvention` field in the options payload.

Ex:

```
const gqlDataProvider = dataProvider(client, {namingConvention: "graphql-default"});
```

If the `graphql-default` naming convention is provided, all field names and variables will be camel cased. Type names will be pascal cased.

### Test plan (required)

Unit tests are included in the PR.

### Closing issues

closes #3482 

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

**Comment by BatuhanW** [comment]
Hello @mattbho, thanks for the great PR, looks great! Will review in detail soon.

**Comment by BatuhanW** [comment]
Btw, can you generate changeset for hasura package with minor version, ideally explaining the usage and motivation.

You can run `npm run changeset`.

**Review by BatuhanW — APPROVED** [review]
LGTM 🚀

**Comment by BatuhanW** [comment]
Oh @mattbho, I overlooked a failing test before approving, could you please check failing specs?

**Comment by mattbho** [comment]
> Oh @mattbho, I overlooked a failing test before approving, could you please check failing specs?

Done!

**Comment by mattbho** [comment]
> Btw, can you generate changeset for hasura package with minor version, ideally explaining the usage and motivation.
> 
> You can run `npm run changeset`.
> 
> https://refine.dev/docs/contributing/#changeset

Done!

**Review by aliemir — APPROVED** [review]
Thank you for the good work @mattbho!! 🙏🎖️ Let's have a final review from @BatuhanW and release this as soon as possible 🚀

**Review by BatuhanW — APPROVED** [review]
🚀 🚀 🚀

**Pull request merged**
