### PR TITLE
feat: Message was shown to the user when chosen more than the count of the stock  #2916

### PR DESCRIPTION
**Pull request by sevkioruc**
…roduct

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

### CODE REVIEW

**Comment by aliemir** [comment]
Hey @sevkioruc, thank you for your effort! Unfortunately, stocks being limited to 5 is just a coincidence 😅Instead of checking for `count >= 6` we should check for the errors in `updateMutate` response and show a warning when we get stock error 🚀 

Hope this is clear 🤔 Can you update the code according to the above? 🙏 🙏

**Comment by sevkioruc** [comment]
Hey @aliemir, I hope I will update code at this night.

**Comment by sevkioruc** [comment]
Hey @aliemir, @omeraplak,
Could you please review the last commit?

**Review by omeraplak — APPROVED** [review]
LGTM! ⚡️

**Review by aliemir — APPROVED** [review]

**Comment by omeraplak** [comment]
Hey @sevkioruc ,
I broke your fork repo while committing for the review :)

My change suggestion was as follows,

CartItem.tsx
```tsx
<Quantity
                 value={quantity}
                 handleRemove={removeItem}
                 handleChange={handleChange}
                 increase={() => increaseQuantity(1)}
                 decrease={() => increaseQuantity(-1)}
                 max={item.variant.inventory_quantity} // here
             />
```

Quantity.tsx
```tsx
  <button
                 type="button"
                 onClick={increase}
                 className={cn(s.actions)}
                 style={{ marginLeft: "-1px" }}
                 disabled={value < 1 || value >= max}
                 title={value < 1 || value >= max ? "Max quantity reached" : ""} // here
             >
```

**Comment by sevkioruc** [comment]
Hey @omeraplak ,
I agree with you. this is better solution.
Can i open a new PR for this issue according to your suggestion?

**Comment by omeraplak** [comment]
> Hey @omeraplak , I agree with you. this is better solution. Can i open a new PR for this issue according to your suggestion?

Yes, please :)

**Pull request closed without merging**
