### PR TITLE
fix(react-table): useTable is adding an eq condition when I use a gte filter (#3824)

### LINKED ISSUE #3824: [BUG] useTable(React Table) is adding an eq condition when I use a gte filter
### Describe the bug

useTable(React Table) is adding an eq condition when I use a gte filter

The useTable function from the react-table package is adding an eq condition when using a gte filter.

when i call:

```typescript
useTable({
   columns,
   refineCoreProps: {
      permanentFilter: [{
         field: "category.id",
         operator: "gte",
         value: 0,
      },],
   },
})
```

That way I can't use the useTable

Below is my jest to reproduce

### Steps To Reproduce

```typescript
import { renderHook, waitFor } from "@testing-library/react";
import { ColumnDef } from "@tanstack/react-table";

import { TestWrapper } from "../../test";
import { useTable } from "./index";

type Post = {
    id: number;
    title: string;
};

const columns: ColumnDef<Post>[] = [
    {
        id: "id",
        header: "ID",
        accessorKey: "id",
    },
    {
        id: "title",
        header: "Title",
        accessorKey: "title",
        meta: {
            filterOperator: "contains",
        },
    },
];

describe("useTable Hook", () => {
    it("It should work successfully with permanentFilter", async () => {
        const { result } = renderHook(
            () =>
                useTable({
                    columns,
                    refineCoreProps: {
                        permanentFilter: [
                            {
                                field: "category.id",
                                operator: "gte",
                                value: 0,
                            },
                        ],
                    },
                }),
            {
                wrapper: TestWrapper({}),
            },
        );

        await waitFor(() => {
            expect(
                !result.current.refineCore.tableQueryResult.isFetching,
            ).toBeTruthy();
        });

        const {
            refineCore: { filters: filtersCore },
        } = result.current;

        expect(filtersCore).toEqual([
            { field: "category.id", operator: "gte", value: 0 },
        ]);
    });
});
```

### Expected behavior

I would expect as a result the filter 
```typescript
[{ field: "category.id", operator: "gte", value: 0 }, ]
```
 but I am getting 
```typescript
[{ field: "category.id", operator: "gte", value: 0 } , { field: "category.id", operator: "eq", value: 0 }, ]
```

### Screenshot

_No response_

### Desktop

_No response_

### Mobile

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by thiagotognoli**
closes #3824

### Self Check before Merge

Please check all items below before review.

-   [X] Corresponding issues are created/updated or not needed
-   [X] Docs are updated/provided or not needed
-   [X] Examples are updated/provided or not needed
-   [X] TypeScript definitions are updated/provided or not needed
-   [X] Tests are updated/provided or not needed
-   [X] Changesets are provided or not needed

### CODE REVIEW

**Comment by omeraplak** [comment]
Hey @thiagotognoli ,
Thank you for creating a PR. We'll review it soon 🚀

**Comment by salihozdemir** [comment]
Hey @thiagotognoli,

I left some comments about how to solve your problem and the PR here: https://github.com/refinedev/refine/issues/3824#issuecomment-1479287745

Can you check and close the PR and issue if your problem is resolved?

**Comment by salihozdemir** [comment]
Hey @thiagotognoli,

I reviewed again your changes with a fresh mind and I think it is good to go. When I first reviewed it, I was worried about the `filterColumn` type, but now I think it is fine. 

Just one thing, can you please add a changeset? You can do it by running `npx changeset` on the root of the project. You can read more about it [here](https://refine.dev/docs/contributing/#changeset).

**Review by salihozdemir — APPROVED** [review]

**Comment by thiagotognoli** [comment]
> Hey @thiagotognoli,
> 
> I reviewed again your changes with a fresh mind and I think it is good to go. When I first reviewed it, I was worried about the `filterColumn` type, but now I think it is fine.
> 
> Just one thing, can you please add a changeset? You can do it by running `npx changeset` on the root of the project. You can read more about it [here](https://refine.dev/docs/contributing/#changeset).



> Hey @thiagotognoli,
> 
> I reviewed again your changes with a fresh mind and I think it is good to go. When I first reviewed it, I was worried about the `filterColumn` type, but now I think it is fine.
> 
> Just one thing, can you please add a changeset? You can do it by running `npx changeset` on the root of the project. You can read more about it [here](https://refine.dev/docs/contributing/#changeset).

Hi @salihozdemir 

Thank you, i will do

**Review by omeraplak — APPROVED** [review]

**Pull request merged**
