### PR TITLE
refactor(remix): upgrade to remix@2

### LINKED ISSUE #5347: [BUG] @refinedev/remix-router doesn't work with Remix v2
### Describe the bug

After installing  "@refinedev/remix-router": "^2.3.0", I get this error
 ```
✘ [ERROR] No matching export in "node_modules/@remix-run/react/dist/esm/index.js" for import "unstable_useBlocker"

    node_modules/@refinedev/remix-router/dist/esm/index.js:158:9:
      158 │ import { unstable_useBlocker as useBlocker } from "@remix-run/rea...
          ╵          ~~~~~~~~~~~~~~~~~~~
```

### Steps To Reproduce

1. Remix 2.3.1
2. Install "@refinedev/remix-router": "^2.3.0"
3. npm run dev

### Expected behavior

Run it without errros

### Screenshot

_No response_

### Desktop

- Mac 13.6
- Chrome  119

### Mobile

_No response_

### Additional Context

I think this error is due to the fact that `unstable_useBlocker` is deprecated in Remix 2.
In general it'd be appreciate it if you could update all Remix examples to Remix v2

### PR DESCRIPTION
**Pull request by rodbs**
This fixes #5347 by removing `unstable_useBlocker` in `@refinedev/remix-router`
`unstable_useBlocker` was dropped in remix 2.3.0 so     `@refinedev/remix-router` wasn't working   when installing remix latest version.

I haven't updated the remix examples. Better for another PR?
 
### Test plan (required)
Run `npm run test`
(I had to add type `any` to `useLoader` to make it work)

### Closing issues

`closes #5347`
 
### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

**Comment by rodbs** [comment]
I'm following the Contribuitng document and when I do `npm run bootstrap:all` I get this error:

```
lerna ERR! npm install --no-save --ignore-scripts exited 1 in 'refinejs-repo'
lerna ERR! npm install --no-save --ignore-scripts stderr:
npm WARN deprecated @types/minipass@3.3.5: This is a stub types definition. minipass provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/lz-string@1.5.0: This is a stub types definition. lz-string provides its own type definitions, so you do not need this installed.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated expression-eval@5.0.1: The expression-eval npm package is no longer maintained. The package was originally published as part of a now-completed personal project, and I do not have incentives to continue maintenance.
npm WARN deprecated i18next-xhr-backend@3.2.2: replaced by i18next-http-backend
npm ERR! code EIDLETIMEOUT
npm ERR! Idle timeout reached for host `registry.npmjs.org:443`

npm ERR! A complete log of this run can be found in: /Users/rodrigo/.npm/_logs/2023-12-08T11_21_36_286Z-debug-0.log
lerna ERR! npm install --no-save --ignore-scripts exited 1 in 'refinejs-repo'
````

and then the build also fail:
```
npm run build:all ✖    1/3 targets failed, including the following:
         - @refinedev/devtools-shared:build
   View structured, searchable error logs at https://nx.app/runs/Fsys5Nxew4

```
```
> @refinedev/devtools-shared@1.1.2 build
> tsup --format esm,cjs,iife --minify --legacy-output

sh: tsup: command not found
```

Is this ok? Can I modify the code/examples this way? (I'm not an expert in lerna and monorepos)

**Comment by rodbs** [comment]
@aliemir 
I've updated @redifnedev/remix-router to 2.4.0
I've updated all the examples making some changes to make it work with remix 2.3.1

**Comment by rodbs** [comment]
@aliemir 
Is there anything to fix here?

**Comment by aliemir** [comment]
> @aliemir 
> 
> Is there anything to fix here?

Sorry for the late reply @rodbs 🙏 I will do a review today in short time. Had a quick look and it looks good, thank you for the good work 🚀🚀

**Review by aliemir — APPROVED** [review]
Thank you for your effort @rodbs! I've just pushed couple of small changes that I don't want to take your time with.

- Had a small linter issue in the `packages/remix/src/unsaved-changes-notifier.tsx`
- You've updated the version of the `@refinedev/remix-router` manually, which is not necessary and will be handled by the changesets.
- Noticed that we have an unused file `packages/remix/src/prompt.tsx`, removed it.
- Noticed a type error in `examples/with-remix-headless` which was due to a redundant `useLoaderData` hook call, removed it.
- Since Remix just released another minor version, I've just updated them all to `2.4.0` from `2.3.1`.

**Comment by rodbs** [comment]
@aliemir 
On thing I guess you've observed:
In every Remix example I had to insert `serverModuleFormat: "cjs"` to make it work (Remix 2 works with `esm` by default). I didn't dig into why this `cjs`was necesary ..

**Review by BatuhanW — APPROVED** [review]

**Comment by aliemir** [comment]
Hey @rodbs, a quick update for you. We've approved the PR, thanks again for your contribution 🎉 

As you can see there are failing e2e tests for the remix examples. This is related to the `@refinedev/cli` and how it handles `remix-serve` command but other than that the underlying issue is here: https://github.com/remix-run/remix/discussions/7586

We'll have a patch for the `@refinedev/cli` which is not actually covering customized cases for the `start` command. This patch will be done before merging this PR (which is due the end of the month for the release cycle). About the patch; we'll be needing a path argument pointing to the build for the `remix-serve` ad will probably make it required for all the apps. Working on a non-breaking fix that will cover the current users and the new users. 

About the `serverModuleFormat: "cjs"`, this is a change we're willing to do and personally I don't think this is a huge deal for Refine users since its actually related with Remix and faced by many users who are migrating from v1 to v2.

For this PR, there's no further changes and updates needed, let's wait for the patch of `@refinedev/cli` and we'll release this with the January Release milestone. 🚀 🚀

**Pull request merged**
