### PR TITLE
feat(docs): update invoicer template page

### PR DESCRIPTION
**Pull request by alicanerdurmaz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [ ] Tests for the changes have been added
- [x] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the new behavior?

[invoice template](https://refine.dev/templates/react-pdf-invoice-generator) description, links, and image is updated

### CODE REVIEW

**Comment by BatuhanW** [comment]
This is a test comment.

/deploy app-crm-minimal, invoicer

**Comment by BatuhanW** [comment]
This is a test comment.

/deploy app-crm-minimal, invoicer

**Review by necatiozmen — APPROVED** [review]

**Pull request merged**
