### PR TITLE
feat(nestjsx-crud): add between operator

### PR DESCRIPTION
**Pull request by mehrabmp**
## PR Checklist

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?
The `between` operator doesn’t work correctly. It uses the `eq` (equal) operator instead of `between`.
## What is the new behavior?
The `between` operator now works as expected and filters values between the specified range.

### CODE REVIEW

**Review by aliemir — COMMENTED** [review]
Hey @mehrabmp thank you for the contribution! Can you create an issue for this and link with this PR? 🙏

**Comment by mehrabmp** [comment]
closes #6334

**Review by BatuhanW — CHANGES_REQUESTED** [review]
Hey @mehrabmp thanks for the PR. Can you add tests?

**Review by BatuhanW — APPROVED** [review]

**Review by aliemir — APPROVED** [review]

**Comment by aliemir** [comment]
Thank you for the contribution @mehrabmp, we'll include this in our next release 🙏

**Pull request merged**
