### PR TITLE
feat(supabase): improve supabase liveprovider #5357

### LINKED ISSUE #5357: [FEAT] Supabase LiveProvider improvements
### Is your feature request related to a problem? Please describe.

Using Supabase client's liveProvider, with `liveMode: "auto"`...

1) On a page featuring a List, where the primary resource has related/child resources, liveProvider subscriptions that are automatically added to watch for changes on child/related resources overwrite other subscriptions on the page, so the only one that actually is left working is the last one to get set up. Naturally, this means the main resource (plus any other related/child resources on the page before this one), do not receive change notification messages. This is actually a bug, caused by every call to `subscribe` using the same channel name of `"any"`.

2) Calls to Supabase's liveProvider's `subscribe` method do not currently handle multiple event types — only the first in the passed `types` param gets used. This is mentioned in the 'Caution' section of https://refine.dev/docs/packages/data-providers/supabase/#supabase-real-time-support, where it says "Multiple subscriptions needs to be made in a single call, which is not supported by the current version of the `@refinedev/supabase` data provider."

### Describe alternatives you've considered

n/a

### Additional context

n/a

### Describe the thing to improve

I have fixed both of the above-mentioned issues.

My changes consist of: 

- Building a proper channel name to send to Supabase, using the (a) `channel` passed in to the call to `subscribe` (which includes the resource name), plus (b) the passed event `types` (sorted, for stability), and additionally (c) a string based upon `params.filters`. This fixes (1) above. Therefore a channel name passed internally to Supabase with the new code might look like `"resources/blog_posts:*:` (assuming no filters here) — as opposed to all subscriptions on the page using `"any"` as their channel name.
- Calling `client.[...].on` for every event in `types` before calling `subscribe` — as opposed to the current code which only called `client.[...].on` once, using `events[0]`.

I've currently done all of this in a swizzled copy of the Supabase data provider, but I will put together a proper pull request, and reference this issue.

### PR DESCRIPTION
**Pull request by jimsmart**
> Please provide enough information so that others can review your pull request:

In Supabase (I used the locally hosted version): 

- Create a user to authenticate with (may not be necessary on cloud-hosted Supabase).
- Create a table `categories`, it will automatically have an `id` field and an `created_on` field — add a field `name` of text type. Enter a few rows of data, e.g. "General", "Information", whatever.
- Create a table `blog_posts`, it will automatically have an `id` field and an `created_on` field — add a field `title` of text type, add a field `category_id`, as a foreign key to `categories.id`. Add a couple of blog posts, assign them to categories.
- Create a table `comments`, it will automatically have an `id` field and an `created_on` field — add a field `content` of text type, add a field `blog_post_id`, as a foreign key to `blog_post.id`. Add a couple of comments, assign them to blog posts.

Create a Refine project, with Supabase as the data provider, configured to point to the Supabase instance above (i.e. appropriate API URL and anon key).

Find the `<Refine [...] >` tag, and add the following: `liveProvider={liveProvider(supabaseClient)}`, and also add `liveMode: "auto",` to the `options`.

Run `npm dev start`

Open a browser, go to your local Refine site on port 3000, and login.

Open a second browser (use a different 'brand' of browser here, e.g. use Firefox previously, and Chrome here, so that there is no sharing of sessions), go to your local Refine site on port 3000, and login.

— Note that now, when viewing any of the main list pages (for blog posts, categories, or comments), all live updating now works as intended, i.e. when viewing the blog posts page, renaming a blog post title works as intended, updating in the other browser window; changing a related resource, e.g. category name, while on the blog posts page, also updates in the other browser, as intended.

Without the changes included in this pull request, some of these things simply do not work as intended.

> Explain the **details** for making this change. What existing problem does the pull request solve?

See issue #5357 for further context.

### Test plan (required)

> Demonstrate the code is solid. If not, please add `WIP:` in its title.

I've added WIP: to the title, just in case. But...

I have tested this locally, on an existing project, where previously enabling the liveProvider in auto mode was quite a buggy experience. With the changes in this pull request, it now works as intended.

> Make sure tests pass. 

— I do not know how to run the test suite for Refine, sorry! I imagine they will run fine though: all existing functionality still works, plus more,, and I doubt there are tests asserting that the previous 'broken' behaviour exists.

### Closing issues

This pull request closes #5357 

### Self Check before Merge

> Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed — done
-   [x] Docs are updated/provided or not needed — I have removed the 'caution' notice from https://refine.dev/docs/packages/data-providers/supabase/#supabase-real-time-support because it is no longer necessary: the Supabase liveProvider now has the mentioned features.
-   [x] Examples are updated/provided or not needed — not needed
-   [x] TypeScript definitions are updated/provided or not needed — not needed
-   [x] Tests are updated/provided or not needed — not needed?
-   [ ] Changesets are provided or not needed — IDK what this means, sorry!

### CODE REVIEW

**Comment by jimsmart** [comment]
Ok, I see this probably needs a changeset — because it is a bugfix and a feature improvement.

Is it possible for someone else (with more knowledge) to do that on my behalf, please?

**Comment by jimsmart** [comment]
Ah, shoot — I see my changes to packages/supabase/src/liveProvider/index.ts appear to have whitespace issues, where I copy pasted my code from the swizzled version. Ooof. 😢 🤷

**Comment by jimsmart** [comment]
> Ah, shoot — I see my changes to packages/supabase/src/liveProvider/index.ts appear to have whitespace issues, where I copy pasted my code from the swizzled version. Ooof. 😢

I have fixed up the whitespace, it now matches the original file — and the code review should be much easier now. Sorry for the noise along the way.

**Comment by BatuhanW** [comment]
Hello @jimsmart, you can see our documentation on how to generate changeset [here](https://refine.dev/docs/further-readings/contributing/#changeset)

Let us know if you have issues, we can do it for you.

**Review by omeraplak — APPROVED** [review]

**Pull request merged**
